---
# tasks file for role_bi_packages_minimum
- name: Include os independent variables.
  include_vars: "vars/main.yml"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: [ never, debug ]

- name: Install packages
  include: 01-packages.yml

- name: Configure role_bi_packages_minimum
  include: 02-configure.yml

